version: "3.8"
services:
  db:
    container_name: mysql
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: password   
  
  flask-app:
    build: ./flask-app
    environment:
      MYSQL_ROOT_PASSWORD: password
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp

    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    